# Generated by Django 6.0.3 on 2026-04-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_expected_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='expected_delivery_date',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
