# Generated by Django 6.0.3 on 2026-05-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
