# Generated by Django 6.0.3 on 2026-05-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_type',
            field=models.CharField(choices=[('ONE_SIZE', 'One Size'), ('SHOE', 'Shoes (1-10)'), ('APPAREL', 'Apparel (S, M, L, XL, XXL)')], default='ONE_SIZE', max_length=20),
        ),
    ]
