# Generated by Django 6.0.3 on 2026-07-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_size_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, help_text='External image link or product link', max_length=1000, null=True),
        ),
    ]
